/*
  Warnings:

  - You are about to drop the column `entidad` on the `inmuebles` table. All the data in the column will be lost.
  - You are about to drop the column `numeroExteriorInterior` on the `inmuebles` table. All the data in the column will be lost.
  - You are about to drop the column `rfi` on the `inmuebles` table. All the data in the column will be lost.
  - You are about to drop the column `ruralSemiurbanoUrbano` on the `inmuebles` table. All the data in the column will be lost.
  - You are about to drop the column `tipo` on the `inmuebles` table. All the data in the column will be lost.
  - You are about to drop the column `tipoNombreVialidad` on the `inmuebles` table. All the data in the column will be lost.
  - The `m2Terreno` column on the `inmuebles` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - The `m2Construccion` column on the `inmuebles` table would be dropped and recreated. This will lead to data loss if there is data in the column.

*/
-- AlterTable
ALTER TABLE "inmuebles" DROP COLUMN "entidad",
DROP COLUMN "numeroExteriorInterior",
DROP COLUMN "rfi",
DROP COLUMN "ruralSemiurbanoUrbano",
DROP COLUMN "tipo",
DROP COLUMN "tipoNombreVialidad",
ADD COLUMN     "aguaPotableHoras" TEXT,
ADD COLUMN     "aireAcondicionado" TEXT,
ADD COLUMN     "alumbradoPublico" TEXT,
ADD COLUMN     "avaluo" DOUBLE PRECISION,
ADD COLUMN     "calefaccion" TEXT,
ADD COLUMN     "catalogado" TEXT,
ADD COLUMN     "categoria" TEXT,
ADD COLUMN     "categoriaDocumento" TEXT,
ADD COLUMN     "cctv" TEXT,
ADD COLUMN     "cedulaInventario" TEXT,
ADD COLUMN     "claveEntidad" TEXT,
ADD COLUMN     "claveInegi" TEXT,
ADD COLUMN     "claveLocalidad" TEXT,
ADD COLUMN     "claveMunicipio" TEXT,
ADD COLUMN     "claveRegimen" TEXT,
ADD COLUMN     "compartido" TEXT,
ADD COLUMN     "constanciaAlineamiento" TEXT,
ADD COLUMN     "constanciaUsoSuelo" TEXT,
ADD COLUMN     "contabilizado" TEXT,
ADD COLUMN     "costoAvaluo" DOUBLE PRECISION,
ADD COLUMN     "cpAdministracionPostal" TEXT,
ADD COLUMN     "cuentaCedulaCatastral" TEXT,
ADD COLUMN     "dictamenFuncionalidad" TEXT,
ADD COLUMN     "dictamenInah" TEXT,
ADD COLUMN     "dictamenInba" TEXT,
ADD COLUMN     "direccionCompleta" TEXT,
ADD COLUMN     "documentoQueAcreditaInicial" TEXT,
ADD COLUMN     "drenaje" TEXT,
ADD COLUMN     "drenajeAlcantarillado" TEXT,
ADD COLUMN     "entreVialidad" TEXT,
ADD COLUMN     "estatusInventario" TEXT,
ADD COLUMN     "fechaAlta" TIMESTAMP(3),
ADD COLUMN     "fechaBaja" TIMESTAMP(3),
ADD COLUMN     "fechaControl" TIMESTAMP(3),
ADD COLUMN     "fechaInscripcionRppf" TIMESTAMP(3),
ADD COLUMN     "fechaInscripcionRppl" TIMESTAMP(3),
ADD COLUMN     "fechaReclasificacion" TIMESTAMP(3),
ADD COLUMN     "fechaReporte" TIMESTAMP(3),
ADD COLUMN     "fechaValorCatastral" TIMESTAMP(3),
ADD COLUMN     "folioRealRppf" TEXT,
ADD COLUMN     "gas" TEXT,
ADD COLUMN     "gradoAprovechamiento" TEXT,
ADD COLUMN     "inahOInba" TEXT,
ADD COLUMN     "interior" TEXT,
ADD COLUMN     "internet" TEXT,
ADD COLUMN     "latitud" DOUBLE PRECISION,
ADD COLUMN     "localidad" TEXT,
ADD COLUMN     "longitud" DOUBLE PRECISION,
ADD COLUMN     "luz" TEXT,
ADD COLUMN     "m2ConstruccionAtencionUsuarios" DOUBLE PRECISION,
ADD COLUMN     "m2ConstruccionBodegas" DOUBLE PRECISION,
ADD COLUMN     "m2ConstruccionManejoPostal" DOUBLE PRECISION,
ADD COLUMN     "m2ConstruccionOficinas" DOUBLE PRECISION,
ADD COLUMN     "m2Ocupado" DOUBLE PRECISION,
ADD COLUMN     "m2TerrenoEstacionamiento" DOUBLE PRECISION,
ADD COLUMN     "m2TerrenoManejoPostal" DOUBLE PRECISION,
ADD COLUMN     "memoriaFotografica" TEXT,
ADD COLUMN     "montoRenta" DOUBLE PRECISION,
ADD COLUMN     "noInscripcionRppl" TEXT,
ADD COLUMN     "noRfi" TEXT,
ADD COLUMN     "noRiuf" TEXT,
ADD COLUMN     "nombre" TEXT,
ADD COLUMN     "nombreVialidad" TEXT,
ADD COLUMN     "numBodegas" INTEGER,
ADD COLUMN     "numCuartosOficinas" INTEGER,
ADD COLUMN     "numEspaciosOtrosUsos" INTEGER,
ADD COLUMN     "numSanitarios" INTEGER,
ADD COLUMN     "numero" TEXT,
ADD COLUMN     "observaciones2025" TEXT,
ADD COLUMN     "padronEstrategico" TEXT,
ADD COLUMN     "pavimentacion" TEXT,
ADD COLUMN     "personalQueOcupa" INTEGER,
ADD COLUMN     "planoArquitectonico" TEXT,
ADD COLUMN     "planoCatastral" TEXT,
ADD COLUMN     "planoTopografico" TEXT,
ADD COLUMN     "propietarioTitular" TEXT,
ADD COLUMN     "referencias" TEXT,
ADD COLUMN     "rppf" TEXT,
ADD COLUMN     "rppl" TEXT,
ADD COLUMN     "seguimiento2026" TEXT,
ADD COLUMN     "situacionEspecialUso" TEXT,
ADD COLUMN     "situacionInmueble" TEXT,
ADD COLUMN     "telefono" TEXT,
ADD COLUMN     "tieneAlineamiento" TEXT,
ADD COLUMN     "tieneCedula" TEXT,
ADD COLUMN     "tieneCedulaCatastral" TEXT,
ADD COLUMN     "tieneDocumento" TEXT,
ADD COLUMN     "tieneInah" TEXT,
ADD COLUMN     "tieneInba" TEXT,
ADD COLUMN     "tienePlanoCatastral" TEXT,
ADD COLUMN     "tieneRfi" TEXT,
ADD COLUMN     "tieneUsoSuelo" TEXT,
ADD COLUMN     "tieneValorCatastral" TEXT,
ADD COLUMN     "tipoAsentamiento" TEXT,
ADD COLUMN     "tipoVialidad" TEXT,
ADD COLUMN     "ubicacionDocumento" TEXT,
ADD COLUMN     "uso" TEXT,
ADD COLUMN     "util" TEXT,
ADD COLUMN     "valorCatastralTotal" DOUBLE PRECISION,
ADD COLUMN     "valorConstruccion" DOUBLE PRECISION,
ADD COLUMN     "valorContable" DOUBLE PRECISION,
ADD COLUMN     "valorTerreno" DOUBLE PRECISION,
ADD COLUMN     "vigenciaDocumento" TEXT,
ADD COLUMN     "yVialidad" TEXT,
ADD COLUMN     "zona" TEXT,
ALTER COLUMN "tipoInmueble" DROP NOT NULL,
DROP COLUMN "m2Terreno",
ADD COLUMN     "m2Terreno" DOUBLE PRECISION,
DROP COLUMN "m2Construccion",
ADD COLUMN     "m2Construccion" DOUBLE PRECISION;
